# config/_default/menu.toml

# Configure social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/braisdev"

  [social.params]
    icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/braisms_dev"

  [social.params]
    icon = "brand-x"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/brais-maneiro-sanchez/"

  [social.params]
    icon = "brand-linkedin"
