# config/_default/related.toml

[params.related]
includeNewer = true
threshold = 60
toLower = false

[[params.related.indices]]
name = "tags"
weight = 100

[[params.related.indices]]
name = "categories"
weight = 200
